# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='unit',
            field=models.CharField(choices=[('Caixa(s)', 'Caixa(s)'), ('Embalagem(ns)', 'Embalagem(ns)'), ('Litro(s)', 'Litro(s)'), ('Quilo(s)', 'Quilo(s)')], default='', max_length=14, verbose_name='Unidade'),
        ),
    ]
