# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20170621_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('service_type', models.CharField(choices=[('Doação', 'Doação'), ('Recebimento', 'Recebimento')], default='Recebimento', max_length=12, verbose_name='Tipo de serviço')),
                ('item', models.CharField(default='', max_length=100, verbose_name='Item')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Donors', verbose_name='Doador')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
                'ordering': ['service_type'],
            },
        ),
    ]
