# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('service_type', models.CharField(choices=[('A', 'Aluguel'), ('C', 'Compra'), ('D', 'Devolução'), ('O', 'Doação'), ('E', 'Extorno'), ('R', 'Recebimento'), ('T', 'Troca')], default='Recebimento', max_length=12)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Doador',
                'verbose_name_plural': 'Doadores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('service_type', models.CharField(choices=[('A', 'Aluguel'), ('C', 'Compra'), ('D', 'Devolução'), ('O', 'Doação'), ('E', 'Extorno'), ('R', 'Recebimento'), ('T', 'Troca')], max_length=12)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='expenses',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Products', verbose_name='Serviço'),
        ),
        migrations.AddField(
            model_name='donations',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Donors', verbose_name='Doador'),
        ),
        migrations.AddField(
            model_name='donations',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Products', verbose_name='Nome'),
        ),
    ]
