# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('service_type', models.CharField(choices=[('Doação', 'Doação'), ('Recebimento', 'Recebimento')], default='Recebimento', max_length=12, verbose_name='Tipo de serviço')),
                ('item', models.CharField(default='', max_length=100, verbose_name='Item')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
            options={
                'ordering': ['service_type'],
                'verbose_name_plural': 'Doações',
                'verbose_name': 'Doação',
            },
        ),
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(default='', max_length=100, verbose_name='Identificador')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Doadores',
                'verbose_name': 'Doador',
            },
        ),
        migrations.AddField(
            model_name='donations',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Donors', verbose_name='Doador'),
        ),
    ]
