# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='price',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='donations',
            name='service_type',
            field=models.CharField(choices=[('Aluguel', 'Aluguel'), ('Compra', 'Compra'), ('Devolução', 'Devolução'), ('Doação', 'Doação'), ('Extorno', 'Extorno'), ('Recebimento', 'Recebimento'), ('Pagamento', 'Pagamento')], default='Recebimento', max_length=12, verbose_name='Tipo de serviço'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='service_type',
            field=models.CharField(choices=[('Aluguel', 'Aluguel'), ('Compra', 'Compra'), ('Devolução', 'Devolução'), ('Doação', 'Doação'), ('Extorno', 'Extorno'), ('Recebimento', 'Recebimento'), ('Pagamento', 'Pagamento')], default='Compra', max_length=12, verbose_name='Tipo de serviço'),
        ),
        migrations.AddField(
            model_name='items',
            name='expense_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Expenses', verbose_name='Nome'),
        ),
    ]
