# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donations',
            options={'ordering': ['service_type'], 'verbose_name': 'Doação', 'verbose_name_plural': 'Doações'},
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['service_type'], 'verbose_name': 'Despesa', 'verbose_name_plural': 'Despesas'},
        ),
        migrations.RemoveField(
            model_name='donations',
            name='name',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='name',
        ),
        migrations.AddField(
            model_name='donations',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='donations',
            name='item',
            field=models.CharField(default='', max_length=100, verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='donors',
            name='slug',
            field=models.SlugField(default='', max_length=100, verbose_name='Identificador'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='item',
            field=models.CharField(default='', max_length=100, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='donations',
            name='service_type',
            field=models.CharField(choices=[('Aluguel', 'Aluguel'), ('Compra', 'Compra'), ('Devolução', 'Devolução'), ('Doação', 'Doação'), ('Extorno', 'Extorno'), ('Recebimento', 'Recebimento'), ('Pagamento', 'Pagamento')], default='Recebimento', max_length=12, verbose_name='Tipo de serviço'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='service_type',
            field=models.CharField(choices=[('Aluguel', 'Aluguel'), ('Compra', 'Compra'), ('Devolução', 'Devolução'), ('Doação', 'Doação'), ('Extorno', 'Extorno'), ('Recebimento', 'Recebimento'), ('Pagamento', 'Pagamento')], default='Compra', max_length=12, verbose_name='Tipo de serviço'),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
