# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='service_type',
            field=models.CharField(choices=[('A', 'Aluguel'), ('C', 'Compra'), ('D', 'Devolução'), ('O', 'Doação'), ('E', 'Extorno'), ('R', 'Recebimento'), ('P', 'Pagamento')], default='R', max_length=12, verbose_name='Tipo de serviço'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='service_type',
            field=models.CharField(choices=[('A', 'Aluguel'), ('C', 'Compra'), ('D', 'Devolução'), ('O', 'Doação'), ('E', 'Extorno'), ('R', 'Recebimento'), ('P', 'Pagamento')], default='C', max_length=12, verbose_name='Tipo de serviço'),
        ),
    ]
