# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20170530_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsDonations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='ItemsExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.RemoveField(
            model_name='items',
            name='expense_id',
        ),
        migrations.AlterModelOptions(
            name='donations',
            options={'ordering': ['service_type'], 'verbose_name': 'Doação', 'verbose_name_plural': 'Doações'},
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['service_type'], 'verbose_name': 'Despesa', 'verbose_name_plural': 'Despesas'},
        ),
        migrations.RemoveField(
            model_name='donations',
            name='name',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='name',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='itemsexpenses',
            name='expense_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Expenses', verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='itemsdonations',
            name='donation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Donations', verbose_name='Nome'),
        ),
    ]
