# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20170610_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expenses',
        ),
        migrations.AlterField(
            model_name='donations',
            name='service_type',
            field=models.CharField(choices=[('Doação', 'Doação'), ('Recebimento', 'Recebimento')], default='Recebimento', max_length=12, verbose_name='Tipo de serviço'),
        ),
    ]
